name: Go Build and Release for Tachyon

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Read version
        id: vars
        run: echo "RELEASE_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build for Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -o tachyon_amd64

      - name: Build for Linux ARM64
        run: GOOS=linux GOARCH=arm64 go build -o tachyon_arm64

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: gh-actions/gh-release@master
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Tachyon Release ${{ env.RELEASE_VERSION }}
          body: New release version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          files: ./tachyon_amd64 ./tachyon_arm64